In [1]:
print("intro to pandas")

intro to pandas

there ate two types of data structure
series
dataframe

In [7]:
import pandas as pd

s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
# data frame
pd = pd.DataFrame({
    'name': ['bilal', 'ali', 'ahmed'],
    'age': [20, 21, 22],
    'city': ['lahore', 'karachi', 'islamabad']
})
pd

    name  age       city
0  bilal   20     lahore
1    ali   21    karachi
2  ahmed   22  islamabad

In [20]:
import pandas as pd

df = pd.read_csv("iris.csv")
 # use correct relative path
df  # Show first 5 rows

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [21]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [22]:
df.describe()  # Get summary statistics of the DataFrame

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [23]:
df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [30]:
# Data selection

df[["sepal.width","petal.width"]]

     sepal.width  petal.width
0            3.5          0.2
1            3.0          0.2
2            3.2          0.2
3            3.1          0.2
4            3.6          0.2
..           ...          ...
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

[150 rows x 2 columns]

In [38]:
df2 = pd.read_csv("data.csv")
df2

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [40]:
df2.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [34]:
df2.dropna()

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [42]:
df2.fillna(0)  # Fill NaN values with 0

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [45]:
df2.rename(columns={"sepal.length": "SL"})

      SL  sepal.width  petal.length  petal.width    variety
0    5.1          3.5           1.4          0.2     Setosa
1    4.9          3.0           1.4          0.2     Setosa
2    4.7          3.2           1.3          0.2     Setosa
3    4.6          3.1           1.5          0.2     Setosa
4    5.0          3.6           1.4          0.2     Setosa
..   ...          ...           ...          ...        ...
145  6.7          3.0           5.2          2.3  Virginica
146  6.3          2.5           5.0          1.9  Virginica
147  6.5          3.0           5.2          2.0  Virginica
148  6.2          3.4           5.4          2.3  Virginica
149  5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [46]:
df2["zeroes"] = [0 for i in range(len(df2))]  # Add a new column with zeroes
df2

     sepal.length  sepal.width  petal.length  petal.width    variety  zeroes
0             5.1          3.5           1.4          0.2     Setosa       0
1             4.9          3.0           1.4          0.2     Setosa       0
2             4.7          3.2           1.3          0.2     Setosa       0
3             4.6          3.1           1.5          0.2     Setosa       0
4             5.0          3.6           1.4          0.2     Setosa       0
..            ...          ...           ...          ...        ...     ...
145           6.7          3.0           5.2          2.3  Virginica       0
146           6.3          2.5           5.0          1.9  Virginica       0
147           6.5          3.0           5.2          2.0  Virginica       0
148           6.2          3.4           5.4          2.3  Virginica       0
149           5.9          3.0           5.1          1.8  Virginica       0

[150 rows x 6 columns]

In [47]:
data = {
    'name': ["bilal", "ali", "ahmed"],
    'age': [20, 21, 22],
    'city': ["lahore", "karachi", "islamabad"]
}

df = pd.DataFrame(data)
df

    name  age       city
0  bilal   20     lahore
1    ali   21    karachi
2  ahmed   22  islamabad

In [48]:
# cteate a data frame of a list dic
data = [
    {"name": "bilal", "age": 20, "city": "lahore"},
    {"name": "ali", "age": 21, "city": "karachi"},
    {"name": "ahmed", "age": 22, "city": "islamabad"}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

    name  age       city
0  bilal   20     lahore
1    ali   21    karachi
2  ahmed   22  islamabad
<class 'pandas.core.frame.DataFrame'>

In [49]:
df.at[2,'name']

'ahmed'

In [50]:
df.iat[2,2]

'islamabad'